version: '2'

services:
    kf2:
        build: .
        container_name: kf2
        # Uncomment this to skip auto-update
        #command: update validate
        #command: update -beta preview validate
        restart: always
        ports:
            - 0.0.0.0:20560:20560/udp
            - 0.0.0.0:27015:27015/udp
            - 0.0.0.0:7777:7777/udp
            - 8080
        environment:
            - KF_BANNER_LINK="http:\/\/art.tripwirecdn.com\/TestItemIcons\/MOTDServer.png"
            - KF_DIFFICULTY=1
            - KF_GAME_LENGTH=1
            - KF_SERVER_NAME="APCS LADZ Public Server"
            - KF_MAP=KF-ZedLanding
            - KF_QUERY_PORT=27015
            - KF_PORT=7777
            - KF_ENABLE_WEB=true
            - KF_ADMIN_PASS=secret
            - KF_WEBADMIN_PORT=8080
            - KF_MOTD="SUP APCS LADZ!"
            - KF_WEBSITE_LINK="https:\/\/killingfloor2.com\/"
        volumes:
            - ./kf2server/:/home/steam/kf2server
            - ./kf2_steamdir/:/home/steam/steam
            - ./game.yml:/home/steam/game.yml:ro
        logging:
            # limit logs retained on host to 25MB
            driver: "json-file"
            options:
                max-size: "500k"
                max-file: "50"
        labels:
          - traefik.http.services.kf2.loadbalancer.server.port=8080
          - traefik.http.routers.kf2.rule=Host(`kf2.sree.io`)
          - traefik.http.routers.kf2.tls=true

networks:
  default:
    external:
      name: traefik
